# libgorak.cmake - Consumer-only configuration for libgorak
#
# This script is for projects that link against libgorak. Do NOT include it
# when building libgorak itself. It defines configuration options (with defaults)
# and a helper to apply them as compile definitions to targets that include
# lgk_tnt.h. It does not create or build any library.

# TNT / lgk_tnt options (defaults shall match lgk_tnt.h)
option(LGK_TNT_NO_ERRNO "don't provide errno-aware macros (removes errno.h and string.h dependencies)" OFF)
option(LGK_TNT_NO_TRACE_SHORTS "don't provide trace shorthand macros (DBG, INF, WRN, ERR, ERRF, ERRFE, ...)" OFF)
option(LGK_TNT_OUTPUT_LEVEL_DYNAMIC "make trace level runtime-configurable" OFF)
set(LGK_TNT_OUTPUT_LEVEL "" CACHE STRING "Trace output level (EMERGENCY, ALERT, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG). If using LGK_TNT_OUTPUT_LEVEL_DYNAMIC, this is the initial value. Defaults to INFO if NDEBUG is set, DEBUG otherwise")
set(LGK_TNT_PRINT_DEFAULT "" CACHE STRING "default function for error output, defaults to \"lgk_tnt_print_stderr\"")
set(LGK_TNT_TRAP_LABEL_PREFIX "" CACHE STRING "prefix for trap labels, defaaults to \"trap\"")
set(LGK_TNT_TRAP_TRACE_LEVEL "" CACHE STRING "default trace level for traps, defaults to \"TRACE_LEVEL_CRITICAL\"")
set(LGK_TNT_PRINT_SYSLOG_FACILITY "" CACHE STRING "syslog facility (when using tnt_print_syslog), defaults to LOG_USER")
set(LGK_TNT_PRINT_SYSLOG_STRBUF_SIZE "" CACHE STRING "Size of string buffer for tnt_print_syslog. Defaults to 1024.")

function(libgorak_apply_header_options target)
    if (LGK_TNT_NO_ERRNO)
        target_compile_definitions(${target} PRIVATE LGK_TNT_NO_ERRNO)
    endif()
    if (LGK_TNT_NO_TRACE_SHORTS)
        target_compile_definitions(${target} PRIVATE LGK_TNT_NO_TRACE_SHORTS)
    endif()
    if (LGK_TNT_OUTPUT_LEVEL_DYNAMIC)
        target_compile_definitions(${target} PRIVATE LGK_TNT_OUTPUT_LEVEL_DYNAMIC)
    endif()
    if (LGK_TNT_OUTPUT_LEVEL)
        target_compile_definitions(${target} PRIVATE LGK_TNT_OUTPUT_LEVEL)
    endif()
    if (LGK_TNT_TRAP_TRACE_LEVEL)
        target_compile_definitions(${target} PRIVATE LGK_TNT_TRAP_TRACE_LEVEL=${LGK_TNT_TRAP_TRACE_LEVEL})
    endif()
    if (LGK_TNT_TRAP_LABEL_PREFIX)
        target_compile_definitions(${target} PRIVATE LGK_TNT_TRAP_LABEL_PREFIX=${LGK_TNT_TRAP_LABEL_PREFIX})
    endif()
    if (LGK_TNT_PRINT_DEFAULT)
        target_compile_definitions(${target} PRIVATE LGK_TNT_PRINT_DEFAULT=${LGK_TNT_PRINT_DEFAULT})
    endif()
    if (LGK_TNT_PRINT_SYSLOG_FACILITY)
        target_compile_definitions(${target} PRIVATE LGK_TNT_PRINT_SYSLOG_FACILITY=${LGK_TNT_PRINT_SYSLOG_FACILITY})
    endif()
    if (LGK_TNT_PRINT_SYSLOG_STRBUF_SIZE)
        target_compile_definitions(${target} PRIVATE LGK_TNT_PRINT_SYSLOG_STRBUF_SIZE=${LGK_TNT_PRINT_SYSLOG_STRBUF_SIZE})
    endif()
endfunction()
